version: "3"

services:
  my-app:
    image: mesto:latest
    platform: linux/amd64
    build:
      context: .
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3000}
      env_file:
        .env
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    networks:
      - awesome

networks:
  awesome:
    driver: bridge
